package com.example.burgershop

const val ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
const val ARG_CATEGORY_NAME = "ARG_CATEGORY_NAME"
const val ARG_CATEGORY_IMAGE_URL = "ARG_CATEGORY_IMAGE_URL"

const val ARG_RECIPE = "ARG_RECIPE"

const val SHARED_PREF_BURGER_SHOP = "PREFERENCE_SET_BURGER_SHOP"
const val SET_ID = "SET_ID"